Add enterprise subsidy to devstack
edx/devstack pull request #84
Opened 2024-11-19 13:25 UTC by mfarhan943

----

I've completed each of the following or determined they are not applicable:

```[tasklist]
### Tasks
- [ ] Add the service in `docker-compose.yml` file, follow `docker-compose.yml` file from the source repo.
- [ ] Add `dev.shell` make command if some extra env variables need to be set
- [ ] Add an entry in `check.sh` if needed
- [ ] Mount volume in `docker-compose-host.yml` file 
- [ ] Add entry in `options.mk` file
- [ ] Create `provision-IDA_NAME.sh` file if needed. Also, add an entry in `provision.sh` file.
- [ ] Create table in `provision.sql` file if needed
- [ ] Add an entry in `repo.sh` file.
- [ ] Add an entry in `service_list.rst` file.
```

2024-11-25 07:29 UTC, iamsobanjaved commented on docker-compose.yml
> +      DB_USER: enterprise001
You can name the user to `subsidy001` as their are multiple enterprise services.

2024-11-25 07:40 UTC, iamsobanjaved reviewed
Just a few suggestions, rest looks good.

2024-11-25 07:40 UTC, iamsobanjaved commented on docker-compose.yml
> +      DB_USER: enterprise001
You can name the user `subsidy001` as there are multiple enterprise services.

2024-11-25 07:40 UTC, iamsobanjaved commented on provision-enterprise-subsidy.sh
> +docker exec -t edx.devstack.enterprise-subsidy bash -c "cd /edx/app/${name}/ && make migrate"
You should use `docker compose exec` and then you don't have to provide the entire container name and instead can only write `enterprsie-subsidy`. You can follow any other provision script for the format.

2024-11-25 07:40 UTC, iamsobanjaved commented on provision-mysql80.sql
> +GRANT ALL ON enterprise_subsidy.* TO 'enterprise001'@'%';
Also, add an entry in `provision.sql`.

2024-11-25 07:40 UTC, iamsobanjaved commented on Makefile
> +	docker exec -it edx.devstack.enterprise-subsidy env TERM=$(TERM) bash -c '/bin/bash'
Use `docker compose exec` here.

2024-11-26 10:39 UTC, mfarhan943 commented
> Just a few suggestions, rest looks good.

I have applied the suggestions.

2025-03-17 08:59 UTC, UsamaSadiq requested changes

2025-03-17 08:59 UTC, UsamaSadiq commented on docker-compose-host.yml
> -      - ${PWD}/py_configuration_files/enterprise_access.py:/edx/app/enterprise-access/license_manager/settings/devstack.py
Why is this file being removed?

2025-03-17 08:59 UTC, UsamaSadiq commented on check.sh
> +if should_check enterprise_subsidy; then
The subsidy service [container](https://github.com/edx/devstack/blob/a6e9652a2dcae89fdb0c3d2674206c470e21c328/docker-compose.yml#L915) is named as `enterprise-subsidy` so shouldn't the check be following instead? 
```suggestion
if should_check enterprise-subsidy; then
```

2025-04-03 13:22 UTC, huniafatima-99 approved these changes

2025-04-04 09:03 UTC, UsamaSadiq approved these changes

2025-04-04 19:05 UTC, merged